<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="6" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-18T01:30:43 IST" name="Suite" finished-at="2025-10-18T01:31:29 IST" duration-ms="45970">
    <groups>
    </groups>
    <test started-at="2025-10-18T01:30:43 IST" name="SubmitOrderTest" finished-at="2025-10-18T01:31:25 IST" duration-ms="41830">
      <class name="rahulshettyacademy.tests.EndToEndTest">
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:rahulshettyacademy.tests.EndToEndTest@15a34df2]" started-at="2025-10-18T01:30:43 IST" name="initializeDriver" finished-at="2025-10-18T01:30:48 IST" duration-ms="4842" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="submitOrderTest(java.util.HashMap)[pri:0, instance:rahulshettyacademy.tests.EndToEndTest@15a34df2]" started-at="2025-10-18T01:30:48 IST" name="submitOrderTest" data-provider="getData" finished-at="2025-10-18T01:31:01 IST" duration-ms="12763" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userPwd=Vishnu@123, userEmail=jdvishnu@gmail.com, coupon=rahulshettyacademy, prodNm=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrderTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:rahulshettyacademy.tests.EndToEndTest@15a34df2]" started-at="2025-10-18T01:31:01 IST" name="closeBrowser" finished-at="2025-10-18T01:31:05 IST" duration-ms="4018" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:rahulshettyacademy.tests.EndToEndTest@15a34df2]" started-at="2025-10-18T01:31:05 IST" name="initializeDriver" finished-at="2025-10-18T01:31:07 IST" duration-ms="1985" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="submitOrderTest(java.util.HashMap)[pri:0, instance:rahulshettyacademy.tests.EndToEndTest@15a34df2]" started-at="2025-10-18T01:31:07 IST" name="submitOrderTest" data-provider="getData" finished-at="2025-10-18T01:31:20 IST" duration-ms="13201" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userPwd=Vishnu@123, userEmail=jdvishnu@gmail.com, coupon=rahulshettyacademy, prodNm=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrderTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:rahulshettyacademy.tests.EndToEndTest@15a34df2]" started-at="2025-10-18T01:31:20 IST" name="closeBrowser" finished-at="2025-10-18T01:31:25 IST" duration-ms="4563" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- rahulshettyacademy.tests.EndToEndTest -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2025-10-18T01:30:43 IST" name="ErrorValidationTest" finished-at="2025-10-18T01:31:29 IST" duration-ms="45970">
      <class name="rahulshettyacademy.tests.errorValidationTest">
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:30:43 IST" name="initializeDriver" finished-at="2025-10-18T01:30:48 IST" duration-ms="5205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method retried="true" signature="prodErrorValidationTest()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:30:48 IST" name="prodErrorValidationTest" finished-at="2025-10-18T01:30:55 IST" duration-ms="6570" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at rahulshettyacademy.tests.errorValidationTest.prodErrorValidationTest(errorValidationTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prodErrorValidationTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:30:55 IST" name="closeBrowser" finished-at="2025-10-18T01:30:59 IST" duration-ms="4033" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:30:59 IST" name="initializeDriver" finished-at="2025-10-18T01:31:01 IST" duration-ms="2376" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="prodErrorValidationTest()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:31:01 IST" name="prodErrorValidationTest" finished-at="2025-10-18T01:31:08 IST" duration-ms="7167" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at rahulshettyacademy.tests.errorValidationTest.prodErrorValidationTest(errorValidationTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prodErrorValidationTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:31:08 IST" name="closeBrowser" finished-at="2025-10-18T01:31:13 IST" duration-ms="4688" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:31:13 IST" name="initializeDriver" finished-at="2025-10-18T01:31:15 IST" duration-ms="1743" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method retried="true" signature="zerrorValidationTest()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:31:15 IST" name="zerrorValidationTest" finished-at="2025-10-18T01:31:17 IST" duration-ms="1785" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successful] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successful] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at rahulshettyacademy.tests.errorValidationTest.zerrorValidationTest(errorValidationTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- zerrorValidationTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:31:17 IST" name="closeBrowser" finished-at="2025-10-18T01:31:21 IST" duration-ms="3987" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="initializeDriver()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:31:21 IST" name="initializeDriver" finished-at="2025-10-18T01:31:23 IST" duration-ms="2008" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeDriver -->
        <test-method signature="zerrorValidationTest()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:31:23 IST" name="zerrorValidationTest" finished-at="2025-10-18T01:31:24 IST" duration-ms="1763" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successful] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successful] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at rahulshettyacademy.tests.errorValidationTest.zerrorValidationTest(errorValidationTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- zerrorValidationTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:rahulshettyacademy.tests.errorValidationTest@5a7fe64f]" started-at="2025-10-18T01:31:25 IST" name="closeBrowser" finished-at="2025-10-18T01:31:29 IST" duration-ms="3937" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- rahulshettyacademy.tests.errorValidationTest -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- Suite -->
</testng-results>
